#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscolaApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EscolaApp")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAluno(Aluno instance);
    partial void UpdateAluno(Aluno instance);
    partial void DeleteAluno(Aluno instance);
    partial void InsertUFCD(UFCD instance);
    partial void UpdateUFCD(UFCD instance);
    partial void DeleteUFCD(UFCD instance);
    partial void InsertAlunos_Email(Alunos_Email instance);
    partial void UpdateAlunos_Email(Alunos_Email instance);
    partial void DeleteAlunos_Email(Alunos_Email instance);
    partial void InsertAlunos_Telefone(Alunos_Telefone instance);
    partial void UpdateAlunos_Telefone(Alunos_Telefone instance);
    partial void DeleteAlunos_Telefone(Alunos_Telefone instance);
    partial void InsertArea(Area instance);
    partial void UpdateArea(Area instance);
    partial void DeleteArea(Area instance);
    partial void InsertCurso(Curso instance);
    partial void UpdateCurso(Curso instance);
    partial void DeleteCurso(Curso instance);
    partial void InsertEmail(Email instance);
    partial void UpdateEmail(Email instance);
    partial void DeleteEmail(Email instance);
    partial void InsertInscrito(Inscrito instance);
    partial void UpdateInscrito(Inscrito instance);
    partial void DeleteInscrito(Inscrito instance);
    partial void InsertNota(Nota instance);
    partial void UpdateNota(Nota instance);
    partial void DeleteNota(Nota instance);
    partial void InsertReferenciai(Referenciai instance);
    partial void UpdateReferenciai(Referenciai instance);
    partial void DeleteReferenciai(Referenciai instance);
    partial void InsertTelefone(Telefone instance);
    partial void UpdateTelefone(Telefone instance);
    partial void DeleteTelefone(Telefone instance);
    partial void InsertTurma(Turma instance);
    partial void UpdateTurma(Turma instance);
    partial void DeleteTurma(Turma instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EscolaAppConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aluno> Alunos
		{
			get
			{
				return this.GetTable<Aluno>();
			}
		}
		
		public System.Data.Linq.Table<UFCD> UFCDs
		{
			get
			{
				return this.GetTable<UFCD>();
			}
		}
		
		public System.Data.Linq.Table<Alunos_Email> Alunos_Emails
		{
			get
			{
				return this.GetTable<Alunos_Email>();
			}
		}
		
		public System.Data.Linq.Table<Alunos_Telefone> Alunos_Telefones
		{
			get
			{
				return this.GetTable<Alunos_Telefone>();
			}
		}
		
		public System.Data.Linq.Table<Area> Areas
		{
			get
			{
				return this.GetTable<Area>();
			}
		}
		
		public System.Data.Linq.Table<Curso> Cursos
		{
			get
			{
				return this.GetTable<Curso>();
			}
		}
		
		public System.Data.Linq.Table<Email> Emails
		{
			get
			{
				return this.GetTable<Email>();
			}
		}
		
		public System.Data.Linq.Table<Inscrito> Inscritos
		{
			get
			{
				return this.GetTable<Inscrito>();
			}
		}
		
		public System.Data.Linq.Table<Nota> Notas
		{
			get
			{
				return this.GetTable<Nota>();
			}
		}
		
		public System.Data.Linq.Table<Referenciai> Referenciais
		{
			get
			{
				return this.GetTable<Referenciai>();
			}
		}
		
		public System.Data.Linq.Table<Telefone> Telefones
		{
			get
			{
				return this.GetTable<Telefone>();
			}
		}
		
		public System.Data.Linq.Table<Turma> Turmas
		{
			get
			{
				return this.GetTable<Turma>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alunos")]
	public partial class Aluno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAluno;
		
		private string _Nome;
		
		private string _Apelido;
		
		private System.DateTime _DataNascimento;
		
		private string _NIF;
		
		private System.DateTime _CreateDate;
		
		private System.DateTime _LastUpdate;
		
		private EntitySet<Alunos_Email> _Alunos_Emails;
		
		private EntitySet<Alunos_Telefone> _Alunos_Telefones;
		
		private EntitySet<Inscrito> _Inscritos;
		
		private EntitySet<Nota> _Notas;
        public override string ToString()
        {
			return Nome + " " + Apelido;
        }

        #region Extensibility Method Definitions
        partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAlunoChanging(int value);
    partial void OnIdAlunoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnApelidoChanging(string value);
    partial void OnApelidoChanged();
    partial void OnDataNascimentoChanging(System.DateTime value);
    partial void OnDataNascimentoChanged();
    partial void OnNIFChanging(string value);
    partial void OnNIFChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.DateTime value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Aluno()
		{
			this._Alunos_Emails = new EntitySet<Alunos_Email>(new Action<Alunos_Email>(this.attach_Alunos_Emails), new Action<Alunos_Email>(this.detach_Alunos_Emails));
			this._Alunos_Telefones = new EntitySet<Alunos_Telefone>(new Action<Alunos_Telefone>(this.attach_Alunos_Telefones), new Action<Alunos_Telefone>(this.detach_Alunos_Telefones));
			this._Inscritos = new EntitySet<Inscrito>(new Action<Inscrito>(this.attach_Inscritos), new Action<Inscrito>(this.detach_Inscritos));
			this._Notas = new EntitySet<Nota>(new Action<Nota>(this.attach_Notas), new Action<Nota>(this.detach_Notas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAluno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAluno
		{
			get
			{
				return this._IdAluno;
			}
			set
			{
				if ((this._IdAluno != value))
				{
					this.OnIdAlunoChanging(value);
					this.SendPropertyChanging();
					this._IdAluno = value;
					this.SendPropertyChanged("IdAluno");
					this.OnIdAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apelido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apelido
		{
			get
			{
				return this._Apelido;
			}
			set
			{
				if ((this._Apelido != value))
				{
					this.OnApelidoChanging(value);
					this.SendPropertyChanging();
					this._Apelido = value;
					this.SendPropertyChanged("Apelido");
					this.OnApelidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascimento", DbType="DateTime2 NOT NULL")]
		public System.DateTime DataNascimento
		{
			get
			{
				return this._DataNascimento;
			}
			set
			{
				if ((this._DataNascimento != value))
				{
					this.OnDataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DataNascimento = value;
					this.SendPropertyChanged("DataNascimento");
					this.OnDataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIF", DbType="NVarChar(9) NOT NULL", CanBeNull=false)]
		public string NIF
		{
			get
			{
				return this._NIF;
			}
			set
			{
				if ((this._NIF != value))
				{
					this.OnNIFChanging(value);
					this.SendPropertyChanging();
					this._NIF = value;
					this.SendPropertyChanged("NIF");
					this.OnNIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2 NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2 NOT NULL")]
		public System.DateTime LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Alunos_Email", Storage="_Alunos_Emails", ThisKey="IdAluno", OtherKey="IdAluno")]
		public EntitySet<Alunos_Email> Alunos_Emails
		{
			get
			{
				return this._Alunos_Emails;
			}
			set
			{
				this._Alunos_Emails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Alunos_Telefone", Storage="_Alunos_Telefones", ThisKey="IdAluno", OtherKey="IdAluno")]
		public EntitySet<Alunos_Telefone> Alunos_Telefones
		{
			get
			{
				return this._Alunos_Telefones;
			}
			set
			{
				this._Alunos_Telefones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Inscrito", Storage="_Inscritos", ThisKey="IdAluno", OtherKey="IdAluno")]
		public EntitySet<Inscrito> Inscritos
		{
			get
			{
				return this._Inscritos;
			}
			set
			{
				this._Inscritos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Nota", Storage="_Notas", ThisKey="IdAluno", OtherKey="IdAluno")]
		public EntitySet<Nota> Notas
		{
			get
			{
				return this._Notas;
			}
			set
			{
				this._Notas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alunos_Emails(Alunos_Email entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = this;
		}
		
		private void detach_Alunos_Emails(Alunos_Email entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = null;
		}
		
		private void attach_Alunos_Telefones(Alunos_Telefone entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = this;
		}
		
		private void detach_Alunos_Telefones(Alunos_Telefone entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = null;
		}
		
		private void attach_Inscritos(Inscrito entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = this;
		}
		
		private void detach_Inscritos(Inscrito entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = null;
		}
		
		private void attach_Notas(Nota entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = this;
		}
		
		private void detach_Notas(Nota entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UFCDs")]
	public partial class UFCD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUFCD;
		
		private string _Designação;
		
		private string _Detalhes;
		
		private int _Duração;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntitySet<Nota> _Notas;
		
		private EntitySet<Referenciai> _Referenciais;

        public override string ToString()
        {
			return $"{Designação}";
        }

        #region Extensibility Method Definitions
        partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUFCDChanging(int value);
    partial void OnIdUFCDChanged();
    partial void OnDesignaçãoChanging(string value);
    partial void OnDesignaçãoChanged();
    partial void OnDetalhesChanging(string value);
    partial void OnDetalhesChanged();
    partial void OnDuraçãoChanging(int value);
    partial void OnDuraçãoChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public UFCD()
		{
			this._Notas = new EntitySet<Nota>(new Action<Nota>(this.attach_Notas), new Action<Nota>(this.detach_Notas));
			this._Referenciais = new EntitySet<Referenciai>(new Action<Referenciai>(this.attach_Referenciais), new Action<Referenciai>(this.detach_Referenciais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUFCD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUFCD
		{
			get
			{
				return this._IdUFCD;
			}
			set
			{
				if ((this._IdUFCD != value))
				{
					this.OnIdUFCDChanging(value);
					this.SendPropertyChanging();
					this._IdUFCD = value;
					this.SendPropertyChanged("IdUFCD");
					this.OnIdUFCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designação", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Designação
		{
			get
			{
				return this._Designação;
			}
			set
			{
				if ((this._Designação != value))
				{
					this.OnDesignaçãoChanging(value);
					this.SendPropertyChanging();
					this._Designação = value;
					this.SendPropertyChanged("Designação");
					this.OnDesignaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalhes", DbType="NVarChar(250)")]
		public string Detalhes
		{
			get
			{
				return this._Detalhes;
			}
			set
			{
				if ((this._Detalhes != value))
				{
					this.OnDetalhesChanging(value);
					this.SendPropertyChanging();
					this._Detalhes = value;
					this.SendPropertyChanged("Detalhes");
					this.OnDetalhesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duração", DbType="Int NOT NULL")]
		public int Duração
		{
			get
			{
				return this._Duração;
			}
			set
			{
				if ((this._Duração != value))
				{
					this.OnDuraçãoChanging(value);
					this.SendPropertyChanging();
					this._Duração = value;
					this.SendPropertyChanged("Duração");
					this.OnDuraçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UFCD_Nota", Storage="_Notas", ThisKey="IdUFCD", OtherKey="IdUFCD")]
		public EntitySet<Nota> Notas
		{
			get
			{
				return this._Notas;
			}
			set
			{
				this._Notas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UFCD_Referenciai", Storage="_Referenciais", ThisKey="IdUFCD", OtherKey="IdUFCD")]
		public EntitySet<Referenciai> Referenciais
		{
			get
			{
				return this._Referenciais;
			}
			set
			{
				this._Referenciais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Notas(Nota entity)
		{
			this.SendPropertyChanging();
			entity.UFCD = this;
		}
		
		private void detach_Notas(Nota entity)
		{
			this.SendPropertyChanging();
			entity.UFCD = null;
		}
		
		private void attach_Referenciais(Referenciai entity)
		{
			this.SendPropertyChanging();
			entity.UFCD = this;
		}
		
		private void detach_Referenciais(Referenciai entity)
		{
			this.SendPropertyChanging();
			entity.UFCD = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alunos_Emails")]
	public partial class Alunos_Email : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdContactoMail;
		
		private int _IdAluno;
		
		private int _IdEmail;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntityRef<Aluno> _Aluno;
		
		private EntityRef<Email> _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdContactoMailChanging(int value);
    partial void OnIdContactoMailChanged();
    partial void OnIdAlunoChanging(int value);
    partial void OnIdAlunoChanged();
    partial void OnIdEmailChanging(int value);
    partial void OnIdEmailChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Alunos_Email()
		{
			this._Aluno = default(EntityRef<Aluno>);
			this._Email = default(EntityRef<Email>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContactoMail", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdContactoMail
		{
			get
			{
				return this._IdContactoMail;
			}
			set
			{
				if ((this._IdContactoMail != value))
				{
					this.OnIdContactoMailChanging(value);
					this.SendPropertyChanging();
					this._IdContactoMail = value;
					this.SendPropertyChanged("IdContactoMail");
					this.OnIdContactoMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAluno", DbType="Int NOT NULL")]
		public int IdAluno
		{
			get
			{
				return this._IdAluno;
			}
			set
			{
				if ((this._IdAluno != value))
				{
					if (this._Aluno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAlunoChanging(value);
					this.SendPropertyChanging();
					this._IdAluno = value;
					this.SendPropertyChanged("IdAluno");
					this.OnIdAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmail", DbType="Int NOT NULL")]
		public int IdEmail
		{
			get
			{
				return this._IdEmail;
			}
			set
			{
				if ((this._IdEmail != value))
				{
					if (this._Email.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEmailChanging(value);
					this.SendPropertyChanging();
					this._IdEmail = value;
					this.SendPropertyChanged("IdEmail");
					this.OnIdEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Alunos_Email", Storage="_Aluno", ThisKey="IdAluno", OtherKey="IdAluno", IsForeignKey=true)]
		public Aluno Aluno
		{
			get
			{
				return this._Aluno.Entity;
			}
			set
			{
				Aluno previousValue = this._Aluno.Entity;
				if (((previousValue != value) 
							|| (this._Aluno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aluno.Entity = null;
						previousValue.Alunos_Emails.Remove(this);
					}
					this._Aluno.Entity = value;
					if ((value != null))
					{
						value.Alunos_Emails.Add(this);
						this._IdAluno = value.IdAluno;
					}
					else
					{
						this._IdAluno = default(int);
					}
					this.SendPropertyChanged("Aluno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Email_Alunos_Email", Storage="_Email", ThisKey="IdEmail", OtherKey="IdEmail", IsForeignKey=true)]
		public Email Email
		{
			get
			{
				return this._Email.Entity;
			}
			set
			{
				Email previousValue = this._Email.Entity;
				if (((previousValue != value) 
							|| (this._Email.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Email.Entity = null;
						previousValue.Alunos_Emails.Remove(this);
					}
					this._Email.Entity = value;
					if ((value != null))
					{
						value.Alunos_Emails.Add(this);
						this._IdEmail = value.IdEmail;
					}
					else
					{
						this._IdEmail = default(int);
					}
					this.SendPropertyChanged("Email");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alunos_Telefones")]
	public partial class Alunos_Telefone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdContactoTelefone;
		
		private int _IdAluno;
		
		private int _IdTelefone;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntityRef<Aluno> _Aluno;
		
		private EntityRef<Telefone> _Telefone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdContactoTelefoneChanging(int value);
    partial void OnIdContactoTelefoneChanged();
    partial void OnIdAlunoChanging(int value);
    partial void OnIdAlunoChanged();
    partial void OnIdTelefoneChanging(int value);
    partial void OnIdTelefoneChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Alunos_Telefone()
		{
			this._Aluno = default(EntityRef<Aluno>);
			this._Telefone = default(EntityRef<Telefone>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContactoTelefone", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdContactoTelefone
		{
			get
			{
				return this._IdContactoTelefone;
			}
			set
			{
				if ((this._IdContactoTelefone != value))
				{
					this.OnIdContactoTelefoneChanging(value);
					this.SendPropertyChanging();
					this._IdContactoTelefone = value;
					this.SendPropertyChanged("IdContactoTelefone");
					this.OnIdContactoTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAluno", DbType="Int NOT NULL")]
		public int IdAluno
		{
			get
			{
				return this._IdAluno;
			}
			set
			{
				if ((this._IdAluno != value))
				{
					if (this._Aluno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAlunoChanging(value);
					this.SendPropertyChanging();
					this._IdAluno = value;
					this.SendPropertyChanged("IdAluno");
					this.OnIdAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTelefone", DbType="Int NOT NULL")]
		public int IdTelefone
		{
			get
			{
				return this._IdTelefone;
			}
			set
			{
				if ((this._IdTelefone != value))
				{
					if (this._Telefone.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTelefoneChanging(value);
					this.SendPropertyChanging();
					this._IdTelefone = value;
					this.SendPropertyChanged("IdTelefone");
					this.OnIdTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Alunos_Telefone", Storage="_Aluno", ThisKey="IdAluno", OtherKey="IdAluno", IsForeignKey=true)]
		public Aluno Aluno
		{
			get
			{
				return this._Aluno.Entity;
			}
			set
			{
				Aluno previousValue = this._Aluno.Entity;
				if (((previousValue != value) 
							|| (this._Aluno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aluno.Entity = null;
						previousValue.Alunos_Telefones.Remove(this);
					}
					this._Aluno.Entity = value;
					if ((value != null))
					{
						value.Alunos_Telefones.Add(this);
						this._IdAluno = value.IdAluno;
					}
					else
					{
						this._IdAluno = default(int);
					}
					this.SendPropertyChanged("Aluno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Telefone_Alunos_Telefone", Storage="_Telefone", ThisKey="IdTelefone", OtherKey="IdTelefone", IsForeignKey=true)]
		public Telefone Telefone
		{
			get
			{
				return this._Telefone.Entity;
			}
			set
			{
				Telefone previousValue = this._Telefone.Entity;
				if (((previousValue != value) 
							|| (this._Telefone.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Telefone.Entity = null;
						previousValue.Alunos_Telefones.Remove(this);
					}
					this._Telefone.Entity = value;
					if ((value != null))
					{
						value.Alunos_Telefones.Add(this);
						this._IdTelefone = value.IdTelefone;
					}
					else
					{
						this._IdTelefone = default(int);
					}
					this.SendPropertyChanged("Telefone");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Areas")]
	public partial class Area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdArea;
		
		private string _Designação;
		
		private string _Detalhes;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntitySet<Curso> _Cursos;
        public override string ToString()
        {
			return Designação;
        }

        #region Extensibility Method Definitions
        partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAreaChanging(int value);
    partial void OnIdAreaChanged();
    partial void OnDesignaçãoChanging(string value);
    partial void OnDesignaçãoChanged();
    partial void OnDetalhesChanging(string value);
    partial void OnDetalhesChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Area()
		{
			this._Cursos = new EntitySet<Curso>(new Action<Curso>(this.attach_Cursos), new Action<Curso>(this.detach_Cursos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArea", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdArea
		{
			get
			{
				return this._IdArea;
			}
			set
			{
				if ((this._IdArea != value))
				{
					this.OnIdAreaChanging(value);
					this.SendPropertyChanging();
					this._IdArea = value;
					this.SendPropertyChanged("IdArea");
					this.OnIdAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designação", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Designação
		{
			get
			{
				return this._Designação;
			}
			set
			{
				if ((this._Designação != value))
				{
					this.OnDesignaçãoChanging(value);
					this.SendPropertyChanging();
					this._Designação = value;
					this.SendPropertyChanged("Designação");
					this.OnDesignaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalhes", DbType="NVarChar(250)")]
		public string Detalhes
		{
			get
			{
				return this._Detalhes;
			}
			set
			{
				if ((this._Detalhes != value))
				{
					this.OnDetalhesChanging(value);
					this.SendPropertyChanging();
					this._Detalhes = value;
					this.SendPropertyChanged("Detalhes");
					this.OnDetalhesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Curso", Storage="_Cursos", ThisKey="IdArea", OtherKey="IdArea")]
		public EntitySet<Curso> Cursos
		{
			get
			{
				return this._Cursos;
			}
			set
			{
				this._Cursos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cursos(Curso entity)
		{
			this.SendPropertyChanging();
			entity.Area = this;
		}
		
		private void detach_Cursos(Curso entity)
		{
			this.SendPropertyChanging();
			entity.Area = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cursos")]
	public partial class Curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCurso;
		
		private int _IdArea;
		
		private string _Designação;
		
		private string _Detalhes;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntitySet<Referenciai> _Referenciais;
		
		private EntitySet<Turma> _Turmas;
		
		private EntityRef<Area> _Area;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCursoChanging(int value);
    partial void OnIdCursoChanged();
    partial void OnIdAreaChanging(int value);
    partial void OnIdAreaChanged();
    partial void OnDesignaçãoChanging(string value);
    partial void OnDesignaçãoChanged();
    partial void OnDetalhesChanging(string value);
    partial void OnDetalhesChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Curso()
		{
			this._Referenciais = new EntitySet<Referenciai>(new Action<Referenciai>(this.attach_Referenciais), new Action<Referenciai>(this.detach_Referenciais));
			this._Turmas = new EntitySet<Turma>(new Action<Turma>(this.attach_Turmas), new Action<Turma>(this.detach_Turmas));
			this._Area = default(EntityRef<Area>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					this.OnIdCursoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso = value;
					this.SendPropertyChanged("IdCurso");
					this.OnIdCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArea", DbType="Int NOT NULL")]
		public int IdArea
		{
			get
			{
				return this._IdArea;
			}
			set
			{
				if ((this._IdArea != value))
				{
					if (this._Area.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAreaChanging(value);
					this.SendPropertyChanging();
					this._IdArea = value;
					this.SendPropertyChanged("IdArea");
					this.OnIdAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designação", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Designação
		{
			get
			{
				return this._Designação;
			}
			set
			{
				if ((this._Designação != value))
				{
					this.OnDesignaçãoChanging(value);
					this.SendPropertyChanging();
					this._Designação = value;
					this.SendPropertyChanged("Designação");
					this.OnDesignaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalhes", DbType="NVarChar(250)")]
		public string Detalhes
		{
			get
			{
				return this._Detalhes;
			}
			set
			{
				if ((this._Detalhes != value))
				{
					this.OnDetalhesChanging(value);
					this.SendPropertyChanging();
					this._Detalhes = value;
					this.SendPropertyChanged("Detalhes");
					this.OnDetalhesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Referenciai", Storage="_Referenciais", ThisKey="IdCurso", OtherKey="IdCurso")]
		public EntitySet<Referenciai> Referenciais
		{
			get
			{
				return this._Referenciais;
			}
			set
			{
				this._Referenciais.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Turma", Storage="_Turmas", ThisKey="IdCurso", OtherKey="IdCurso")]
		public EntitySet<Turma> Turmas
		{
			get
			{
				return this._Turmas;
			}
			set
			{
				this._Turmas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Curso", Storage="_Area", ThisKey="IdArea", OtherKey="IdArea", IsForeignKey=true)]
		public Area Area
		{
			get
			{
				return this._Area.Entity;
			}
			set
			{
				Area previousValue = this._Area.Entity;
				if (((previousValue != value) 
							|| (this._Area.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Area.Entity = null;
						previousValue.Cursos.Remove(this);
					}
					this._Area.Entity = value;
					if ((value != null))
					{
						value.Cursos.Add(this);
						this._IdArea = value.IdArea;
					}
					else
					{
						this._IdArea = default(int);
					}
					this.SendPropertyChanged("Area");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Referenciais(Referenciai entity)
		{
			this.SendPropertyChanging();
			entity.Curso = this;
		}
		
		private void detach_Referenciais(Referenciai entity)
		{
			this.SendPropertyChanging();
			entity.Curso = null;
		}
		
		private void attach_Turmas(Turma entity)
		{
			this.SendPropertyChanging();
			entity.Curso = this;
		}
		
		private void detach_Turmas(Turma entity)
		{
			this.SendPropertyChanging();
			entity.Curso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Emails")]
	public partial class Email : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEmail;
		
		private string _Email1;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntitySet<Alunos_Email> _Alunos_Emails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEmailChanging(int value);
    partial void OnIdEmailChanged();
    partial void OnEmail1Changing(string value);
    partial void OnEmail1Changed();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Email()
		{
			this._Alunos_Emails = new EntitySet<Alunos_Email>(new Action<Alunos_Email>(this.attach_Alunos_Emails), new Action<Alunos_Email>(this.detach_Alunos_Emails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmail", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEmail
		{
			get
			{
				return this._IdEmail;
			}
			set
			{
				if ((this._IdEmail != value))
				{
					this.OnIdEmailChanging(value);
					this.SendPropertyChanging();
					this._IdEmail = value;
					this.SendPropertyChanged("IdEmail");
					this.OnIdEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Email", Storage="_Email1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email1
		{
			get
			{
				return this._Email1;
			}
			set
			{
				if ((this._Email1 != value))
				{
					this.OnEmail1Changing(value);
					this.SendPropertyChanging();
					this._Email1 = value;
					this.SendPropertyChanged("Email1");
					this.OnEmail1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Email_Alunos_Email", Storage="_Alunos_Emails", ThisKey="IdEmail", OtherKey="IdEmail")]
		public EntitySet<Alunos_Email> Alunos_Emails
		{
			get
			{
				return this._Alunos_Emails;
			}
			set
			{
				this._Alunos_Emails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alunos_Emails(Alunos_Email entity)
		{
			this.SendPropertyChanging();
			entity.Email = this;
		}
		
		private void detach_Alunos_Emails(Alunos_Email entity)
		{
			this.SendPropertyChanging();
			entity.Email = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inscritos")]
	public partial class Inscrito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdInscricao;
		
		private int _IdTurma;
		
		private int _IdAluno;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntityRef<Aluno> _Aluno;
		
		private EntityRef<Turma> _Turma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdInscricaoChanging(int value);
    partial void OnIdInscricaoChanged();
    partial void OnIdTurmaChanging(int value);
    partial void OnIdTurmaChanged();
    partial void OnIdAlunoChanging(int value);
    partial void OnIdAlunoChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Inscrito()
		{
			this._Aluno = default(EntityRef<Aluno>);
			this._Turma = default(EntityRef<Turma>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInscricao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdInscricao
		{
			get
			{
				return this._IdInscricao;
			}
			set
			{
				if ((this._IdInscricao != value))
				{
					this.OnIdInscricaoChanging(value);
					this.SendPropertyChanging();
					this._IdInscricao = value;
					this.SendPropertyChanged("IdInscricao");
					this.OnIdInscricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTurma", DbType="Int NOT NULL")]
		public int IdTurma
		{
			get
			{
				return this._IdTurma;
			}
			set
			{
				if ((this._IdTurma != value))
				{
					if (this._Turma.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTurmaChanging(value);
					this.SendPropertyChanging();
					this._IdTurma = value;
					this.SendPropertyChanged("IdTurma");
					this.OnIdTurmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAluno", DbType="Int NOT NULL")]
		public int IdAluno
		{
			get
			{
				return this._IdAluno;
			}
			set
			{
				if ((this._IdAluno != value))
				{
					if (this._Aluno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAlunoChanging(value);
					this.SendPropertyChanging();
					this._IdAluno = value;
					this.SendPropertyChanged("IdAluno");
					this.OnIdAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Inscrito", Storage="_Aluno", ThisKey="IdAluno", OtherKey="IdAluno", IsForeignKey=true)]
		public Aluno Aluno
		{
			get
			{
				return this._Aluno.Entity;
			}
			set
			{
				Aluno previousValue = this._Aluno.Entity;
				if (((previousValue != value) 
							|| (this._Aluno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aluno.Entity = null;
						previousValue.Inscritos.Remove(this);
					}
					this._Aluno.Entity = value;
					if ((value != null))
					{
						value.Inscritos.Add(this);
						this._IdAluno = value.IdAluno;
					}
					else
					{
						this._IdAluno = default(int);
					}
					this.SendPropertyChanged("Aluno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Turma_Inscrito", Storage="_Turma", ThisKey="IdTurma", OtherKey="IdTurma", IsForeignKey=true)]
		public Turma Turma
		{
			get
			{
				return this._Turma.Entity;
			}
			set
			{
				Turma previousValue = this._Turma.Entity;
				if (((previousValue != value) 
							|| (this._Turma.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Turma.Entity = null;
						previousValue.Inscritos.Remove(this);
					}
					this._Turma.Entity = value;
					if ((value != null))
					{
						value.Inscritos.Add(this);
						this._IdTurma = value.IdTurma;
					}
					else
					{
						this._IdTurma = default(int);
					}
					this.SendPropertyChanged("Turma");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notas")]
	public partial class Nota : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNota;
		
		private int _IdAluno;
		
		private int _IdUFCD;
		
		private int _Nota1;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntityRef<Aluno> _Aluno;
		
		private EntityRef<UFCD> _UFCD;

        public override string ToString()
        {
			return $"{UFCD.Designação} - {Nota1}";
        }

        #region Extensibility Method Definitions
        partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNotaChanging(int value);
    partial void OnIdNotaChanged();
    partial void OnIdAlunoChanging(int value);
    partial void OnIdAlunoChanged();
    partial void OnIdUFCDChanging(int value);
    partial void OnIdUFCDChanged();
    partial void OnNota1Changing(int value);
    partial void OnNota1Changed();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Nota()
		{
			this._Aluno = default(EntityRef<Aluno>);
			this._UFCD = default(EntityRef<UFCD>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNota", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdNota
		{
			get
			{
				return this._IdNota;
			}
			set
			{
				if ((this._IdNota != value))
				{
					this.OnIdNotaChanging(value);
					this.SendPropertyChanging();
					this._IdNota = value;
					this.SendPropertyChanged("IdNota");
					this.OnIdNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAluno", DbType="Int NOT NULL")]
		public int IdAluno
		{
			get
			{
				return this._IdAluno;
			}
			set
			{
				if ((this._IdAluno != value))
				{
					if (this._Aluno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAlunoChanging(value);
					this.SendPropertyChanging();
					this._IdAluno = value;
					this.SendPropertyChanged("IdAluno");
					this.OnIdAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUFCD", DbType="Int NOT NULL")]
		public int IdUFCD
		{
			get
			{
				return this._IdUFCD;
			}
			set
			{
				if ((this._IdUFCD != value))
				{
					if (this._UFCD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUFCDChanging(value);
					this.SendPropertyChanging();
					this._IdUFCD = value;
					this.SendPropertyChanged("IdUFCD");
					this.OnIdUFCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Nota", Storage="_Nota1", DbType="Int NOT NULL")]
		public int Nota1
		{
			get
			{
				return this._Nota1;
			}
			set
			{
				if ((this._Nota1 != value))
				{
					this.OnNota1Changing(value);
					this.SendPropertyChanging();
					this._Nota1 = value;
					this.SendPropertyChanged("Nota1");
					this.OnNota1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Nota", Storage="_Aluno", ThisKey="IdAluno", OtherKey="IdAluno", IsForeignKey=true)]
		public Aluno Aluno
		{
			get
			{
				return this._Aluno.Entity;
			}
			set
			{
				Aluno previousValue = this._Aluno.Entity;
				if (((previousValue != value) 
							|| (this._Aluno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aluno.Entity = null;
						previousValue.Notas.Remove(this);
					}
					this._Aluno.Entity = value;
					if ((value != null))
					{
						value.Notas.Add(this);
						this._IdAluno = value.IdAluno;
					}
					else
					{
						this._IdAluno = default(int);
					}
					this.SendPropertyChanged("Aluno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UFCD_Nota", Storage="_UFCD", ThisKey="IdUFCD", OtherKey="IdUFCD", IsForeignKey=true)]
		public UFCD UFCD
		{
			get
			{
				return this._UFCD.Entity;
			}
			set
			{
				UFCD previousValue = this._UFCD.Entity;
				if (((previousValue != value) 
							|| (this._UFCD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UFCD.Entity = null;
						previousValue.Notas.Remove(this);
					}
					this._UFCD.Entity = value;
					if ((value != null))
					{
						value.Notas.Add(this);
						this._IdUFCD = value.IdUFCD;
					}
					else
					{
						this._IdUFCD = default(int);
					}
					this.SendPropertyChanged("UFCD");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Referenciais")]
	public partial class Referenciai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdReferencial;
		
		private int _IdCurso;
		
		private int _IdUFCD;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntityRef<Curso> _Curso;
		
		private EntityRef<UFCD> _UFCD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdReferencialChanging(int value);
    partial void OnIdReferencialChanged();
    partial void OnIdCursoChanging(int value);
    partial void OnIdCursoChanged();
    partial void OnIdUFCDChanging(int value);
    partial void OnIdUFCDChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Referenciai()
		{
			this._Curso = default(EntityRef<Curso>);
			this._UFCD = default(EntityRef<UFCD>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReferencial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdReferencial
		{
			get
			{
				return this._IdReferencial;
			}
			set
			{
				if ((this._IdReferencial != value))
				{
					this.OnIdReferencialChanging(value);
					this.SendPropertyChanging();
					this._IdReferencial = value;
					this.SendPropertyChanged("IdReferencial");
					this.OnIdReferencialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", DbType="Int NOT NULL")]
		public int IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					if (this._Curso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCursoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso = value;
					this.SendPropertyChanged("IdCurso");
					this.OnIdCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUFCD", DbType="Int NOT NULL")]
		public int IdUFCD
		{
			get
			{
				return this._IdUFCD;
			}
			set
			{
				if ((this._IdUFCD != value))
				{
					if (this._UFCD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUFCDChanging(value);
					this.SendPropertyChanging();
					this._IdUFCD = value;
					this.SendPropertyChanged("IdUFCD");
					this.OnIdUFCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Referenciai", Storage="_Curso", ThisKey="IdCurso", OtherKey="IdCurso", IsForeignKey=true)]
		public Curso Curso
		{
			get
			{
				return this._Curso.Entity;
			}
			set
			{
				Curso previousValue = this._Curso.Entity;
				if (((previousValue != value) 
							|| (this._Curso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Curso.Entity = null;
						previousValue.Referenciais.Remove(this);
					}
					this._Curso.Entity = value;
					if ((value != null))
					{
						value.Referenciais.Add(this);
						this._IdCurso = value.IdCurso;
					}
					else
					{
						this._IdCurso = default(int);
					}
					this.SendPropertyChanged("Curso");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UFCD_Referenciai", Storage="_UFCD", ThisKey="IdUFCD", OtherKey="IdUFCD", IsForeignKey=true)]
		public UFCD UFCD
		{
			get
			{
				return this._UFCD.Entity;
			}
			set
			{
				UFCD previousValue = this._UFCD.Entity;
				if (((previousValue != value) 
							|| (this._UFCD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UFCD.Entity = null;
						previousValue.Referenciais.Remove(this);
					}
					this._UFCD.Entity = value;
					if ((value != null))
					{
						value.Referenciais.Add(this);
						this._IdUFCD = value.IdUFCD;
					}
					else
					{
						this._IdUFCD = default(int);
					}
					this.SendPropertyChanged("UFCD");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Telefones")]
	public partial class Telefone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTelefone;
		
		private string _Telefone1;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntitySet<Alunos_Telefone> _Alunos_Telefones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTelefoneChanging(int value);
    partial void OnIdTelefoneChanged();
    partial void OnTelefone1Changing(string value);
    partial void OnTelefone1Changed();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Telefone()
		{
			this._Alunos_Telefones = new EntitySet<Alunos_Telefone>(new Action<Alunos_Telefone>(this.attach_Alunos_Telefones), new Action<Alunos_Telefone>(this.detach_Alunos_Telefones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTelefone", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTelefone
		{
			get
			{
				return this._IdTelefone;
			}
			set
			{
				if ((this._IdTelefone != value))
				{
					this.OnIdTelefoneChanging(value);
					this.SendPropertyChanging();
					this._IdTelefone = value;
					this.SendPropertyChanged("IdTelefone");
					this.OnIdTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Telefone", Storage="_Telefone1", DbType="NVarChar(9) NOT NULL", CanBeNull=false)]
		public string Telefone1
		{
			get
			{
				return this._Telefone1;
			}
			set
			{
				if ((this._Telefone1 != value))
				{
					this.OnTelefone1Changing(value);
					this.SendPropertyChanging();
					this._Telefone1 = value;
					this.SendPropertyChanged("Telefone1");
					this.OnTelefone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Telefone_Alunos_Telefone", Storage="_Alunos_Telefones", ThisKey="IdTelefone", OtherKey="IdTelefone")]
		public EntitySet<Alunos_Telefone> Alunos_Telefones
		{
			get
			{
				return this._Alunos_Telefones;
			}
			set
			{
				this._Alunos_Telefones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alunos_Telefones(Alunos_Telefone entity)
		{
			this.SendPropertyChanging();
			entity.Telefone = this;
		}
		
		private void detach_Alunos_Telefones(Alunos_Telefone entity)
		{
			this.SendPropertyChanging();
			entity.Telefone = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Turmas")]
	public partial class Turma : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTurma;
		
		private int _IdCurso;
		
		private string _Designação;
		
		private System.Nullable<System.DateTime> _DataInicio;
		
		private System.Nullable<System.DateTime> _DataFim;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private EntitySet<Inscrito> _Inscritos;
		
		private EntityRef<Curso> _Curso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTurmaChanging(int value);
    partial void OnIdTurmaChanged();
    partial void OnIdCursoChanging(int value);
    partial void OnIdCursoChanged();
    partial void OnDesignaçãoChanging(string value);
    partial void OnDesignaçãoChanged();
    partial void OnDataInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnDataInicioChanged();
    partial void OnDataFimChanging(System.Nullable<System.DateTime> value);
    partial void OnDataFimChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public Turma()
		{
			this._Inscritos = new EntitySet<Inscrito>(new Action<Inscrito>(this.attach_Inscritos), new Action<Inscrito>(this.detach_Inscritos));
			this._Curso = default(EntityRef<Curso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTurma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTurma
		{
			get
			{
				return this._IdTurma;
			}
			set
			{
				if ((this._IdTurma != value))
				{
					this.OnIdTurmaChanging(value);
					this.SendPropertyChanging();
					this._IdTurma = value;
					this.SendPropertyChanged("IdTurma");
					this.OnIdTurmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", DbType="Int NOT NULL")]
		public int IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					if (this._Curso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCursoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso = value;
					this.SendPropertyChanged("IdCurso");
					this.OnIdCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designação", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Designação
		{
			get
			{
				return this._Designação;
			}
			set
			{
				if ((this._Designação != value))
				{
					this.OnDesignaçãoChanging(value);
					this.SendPropertyChanging();
					this._Designação = value;
					this.SendPropertyChanged("Designação");
					this.OnDesignaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInicio", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DataInicio
		{
			get
			{
				return this._DataInicio;
			}
			set
			{
				if ((this._DataInicio != value))
				{
					this.OnDataInicioChanging(value);
					this.SendPropertyChanging();
					this._DataInicio = value;
					this.SendPropertyChanged("DataInicio");
					this.OnDataInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataFim", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DataFim
		{
			get
			{
				return this._DataFim;
			}
			set
			{
				if ((this._DataFim != value))
				{
					this.OnDataFimChanging(value);
					this.SendPropertyChanging();
					this._DataFim = value;
					this.SendPropertyChanged("DataFim");
					this.OnDataFimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Turma_Inscrito", Storage="_Inscritos", ThisKey="IdTurma", OtherKey="IdTurma")]
		public EntitySet<Inscrito> Inscritos
		{
			get
			{
				return this._Inscritos;
			}
			set
			{
				this._Inscritos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Turma", Storage="_Curso", ThisKey="IdCurso", OtherKey="IdCurso", IsForeignKey=true)]
		public Curso Curso
		{
			get
			{
				return this._Curso.Entity;
			}
			set
			{
				Curso previousValue = this._Curso.Entity;
				if (((previousValue != value) 
							|| (this._Curso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Curso.Entity = null;
						previousValue.Turmas.Remove(this);
					}
					this._Curso.Entity = value;
					if ((value != null))
					{
						value.Turmas.Add(this);
						this._IdCurso = value.IdCurso;
					}
					else
					{
						this._IdCurso = default(int);
					}
					this.SendPropertyChanged("Curso");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Inscritos(Inscrito entity)
		{
			this.SendPropertyChanging();
			entity.Turma = this;
		}
		
		private void detach_Inscritos(Inscrito entity)
		{
			this.SendPropertyChanging();
			entity.Turma = null;
		}
	}
}
#pragma warning restore 1591
